### PR TITLE
Create candy_i18n_de_DE.properties

### PR DESCRIPTION
**Pull request by strzonnek**
added German translation

### CODE REVIEW

**Comment by guusdk** [comment]
Hi! Thanks for this! Can you please rename the file to `candy_i18n_de.properties`, otherwise Openfire will not pick it up by default.

**Comment by strzonnek** [comment]
> Hi! Thanks for this! Can you please rename the file to `candy_i18n_de.properties`, otherwise Openfire will not pick it up by default.

I wasn't sure about the naming, because of the existing Russian file name.
Regards, Stephan

**Comment by strzonnek** [comment]
@guusdk would you mind to have another look?
Thanks, Stephan

**Comment by guusdk** [comment]
It now partially works, but some properties are still in English:

- `config.page.debug.enabled=Enabled`
- `config.page.debug.enabled_info=Debug information will be printed to the Javascript console of the client browser.`
- `config.page.debug.disabled=Disabled`
- `config.page.debug.disabled_info=Client-sided debug information will not be generated.`
- `config.page.autojoin.description=When using the Candy web chat interface, a user will automatically join the group chat rooms listed in the following table. Use the form below to change the list of rooms that are automatically joined.`

I have pushed a modification to the changelog file to your branch. Do you want to add the missing translations?

**Comment by strzonnek** [comment]
@guusdk sorry, I totally missed, that you replied

**Pull request merged**
